### ISSUE TITLE
Webdav用户名密码错误

### ISSUE THREAD

**Issue by dralausky** [hbrwang/Lavcode#4]
你好
我用webdav登录显示用户名密码错误，但是用户密码都是正确的，其他软件 ，或者浏览器登录都是正常的。

**Comment by hal-wang** [comment]
> 你好 我用webdav登录显示用户名密码错误，但是用户密码都是正确的，其他软件 ，或者浏览器登录都是正常的。

能否说下是哪家的网盘？

**Comment by dralausky** [comment]
Hi 用的是webdav server ,就是这上面的，用go语言写的那个服务器，链接如下。https://github.com/hacdias/webdav

**Comment by hal-wang** [comment]
你好，很抱歉那么久才真正的解决这个问题，这边测试你说的这个webdav是可以正常同步的，测试相关版本：

- hacdias/webdav 版本：[Release 4.1.1](https://github.com/hacdias/webdav/releases/tag/v4.1.1)
- Lavcode 版本：`0.2.4`、`1.0.1 Beta`
- 服务端环境：`Windows 11 21H2`、`Windows Server 2019`

**配置文件（cfg.yaml）内容：**

```
# Server related settings
address: 0.0.0.0
port: 80
auth: true
tls: false
prefix: /dav

scope: .
modify: true
rules: []

cors:
  enabled: false
  credentials: false

users:
  - username: admin
    password: admin
    scope: .
```

**Lavcode 设置：**

![image](https://user-images.githubusercontent.com/39717597/147935087-3033217e-b3f7-4033-9bbb-93cfb74d45e7.png)

**点击“本地覆盖云端”运行内容：**

_`Lavcode` 文件夹是自动生成的_


![image](https://user-images.githubusercontent.com/39717597/147934857-8c6c195e-47c2-4120-8266-681f5ea44ec5.png)
